# Generated by Django 4.2.5 on 2023-09-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('None', 'None'), ('FE', 'Frontend'), ('BE', 'Backend'), ('API', 'API'), ('DB', 'Database'), ('FR', 'Framework'), ('T', 'Testing'), ('UIUX', 'UI/UX')], default='None', max_length=4),
        ),
    ]
