# Generated by Django 4.2.5 on 2023-09-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_task_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
