# Generated by Django 4.2.5 on 2023-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_task_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_created',
            new_name='time_moved',
        ),
    ]
