# Generated by Django 4.2.5 on 2023-09-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_task_tag'),
        ('kanban', '0004_rename_time_created_task_time_moved'),
    ]

    operations = [
    ]
