# Generated by Django 4.2.5 on 2023-09-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_merge_20230912_1439'),
        ('kanban', '0005_merge_20230912_1500'),
    ]

    operations = [
    ]
