# Generated by Django 4.2.5 on 2023-09-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_merge_20230913_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('IP', 'Important'), ('UR', 'Urgent'), ('IU', 'Important & Urgent')], default='MD', max_length=2),
        ),
    ]
