# Generated by Django 4.2.5 on 2023-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_task_priority'),
        ('kanban', '0007_alter_task_priority'),
        ('kanban', '0007_task_points_alter_task_priority'),
    ]

    operations = [
    ]
