# Generated by Django 4.2.5 on 2023-09-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_list_remove_task_board_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.board'),
        ),
    ]
