# Generated by Django 4.2.5 on 2023-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0010_list_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
