# Generated by Django 4.2.5 on 2023-10-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_alter_list_order_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['order']},
        ),
    ]
