# Generated by Django 4.2.5 on 2023-10-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_alter_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
