# Generated by Django 4.2.5 on 2023-10-17 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_board_end_date_board_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='board',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
