# Generated by Django 4.2.5 on 2023-10-17 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0015_remove_board_end_date_alter_board_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 9, 17)),
        ),
        migrations.AlterField(
            model_name='board',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
