# Generated by Django 4.2.5 on 2023-10-17 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0016_board_end_date_alter_board_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 16)),
        ),
    ]
