# Generated by Django 4.2.5 on 2023-10-17 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0017_task_date_completed_task_hours_spent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_completed',
            new_name='completion_date',
        ),
        migrations.AlterField(
            model_name='board',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 17)),
        ),
    ]
