# Generated by Django 4.2.5 on 2023-10-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0018_rename_date_completed_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_spent',
            field=models.IntegerField(default=0),
        ),
    ]
