# Generated by Django 4.2.5 on 2023-10-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0019_alter_task_hours_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_progress', models.JSONField(default=dict)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sprint', 'user')},
            },
        ),
    ]
