# Generated by Django 4.2.5 on 2023-10-17 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0020_sprintparticipation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprintparticipation',
            old_name='weekly_progress',
            new_name='daily_progress',
        ),
        migrations.AlterField(
            model_name='board',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 10, 24)),
        ),
    ]
