# Generated by Django 4.2.5 on 2023-10-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0023_alter_board_end_date_timespent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSpent',
        ),
    ]
